version: "3.8"

services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "${BLUE_HOST_PORT}:3000"
    healthcheck:
      test: ["CMD", "wget", "-q","-O","-", "http://localhost:3000/healthz"]
      interval: 3s
      timeout: 2s
      retries: 2
      start_period: 2s

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "${GREEN_HOST_PORT}:3000"
    healthcheck:
      test: ["CMD", "wget", "-q","-O","-", "http://localhost:3000/healthz"]
      interval: 3s
      timeout: 2s
      retries: 2
      start_period: 2s

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_stage2
    ports:
      - "${NGINX_HOST_PORT}:80"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
